version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    commit-message:
      prefix: "[pnpm] "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    commit-message:
      prefix: "[actions] "

  - package-ecosystem: npm
    directory: /playground
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test/fixtures/basic
    schedule:
      interval: daily
