allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/unenv-preset@2.16.2'
  - '@cloudflare/workerd-darwin-64@1.20260921.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260921.1'
  - '@cloudflare/workerd-linux-64@1.20260921.1'
  - '@cloudflare/workerd-linux-arm64@1.20260921.1'
  - '@cloudflare/workerd-windows-64@1.20260921.1'
  - miniflare@5.20260921.0-alpha
  - workerd@1.20260921.1
  - wrangler@4.136.1
